name: SwiftLint

on:
  pull_request:
    branches:
      - develop
      - master
jobs:
    SwiftLint:
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2

        - name: Run Swiftlint
        run: |
            swiftlint lint --strict --quiet
