name: SwiftLint

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/swift.yml'
      - '.swift.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Swiftlint
      run: |
        swiftlint lint --strict --quiet
