name: SwiftLint

on:
  pull_request:

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - name: Link SwiftLint or install it
        run: brew link --overwrite swiftlint || brew install swiftlint || brew link --overwrite swiftlint
      - name: SwiftLint
        run: |
          swiftlint . --strict --quiet
